# Generated by Django 5.1.4 on 2025-05-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
