# Generated by Django 5.1.4 on 2025-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0002_project_thumbnail_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='site_geometry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('residential', 'Residential Project'), ('acoustic', 'Acoustic Project'), ('urban', 'Urban Planning Project')], default='residential', max_length=50),
        ),
    ]
