# Generated by Django 5.1.4 on 2025-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0003_project_location_project_site_geometry_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='relative_location',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
