# Generated by Django 5.1.4 on 2025-05-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0004_remove_project_location_project_relative_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_path',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
