# Generated by Django 5.1.4 on 2025-06-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0005_project_building_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='site_geometry',
            new_name='site_bounds',
        ),
    ]
