# Generated by Django 5.1.4 on 2025-06-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0006_rename_site_geometry_project_site_bounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='building_path',
            new_name='site_envelope',
        ),
    ]
