# Generated by Django 5.1.4 on 2025-06-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0007_rename_building_path_project_site_envelope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='relative_location',
            new_name='blocks_envelope',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
    ]
