# Generated by Django 5.1.4 on 2025-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_io', '0008_rename_relative_location_project_blocks_envelope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='map_style',
            field=models.CharField(default='mapbox/light-v11', max_length=100),
        ),
    ]
